.TH "tests Directory Reference" 3 "Mon Mar 24 2014" "Version 0.95" "CUnit Test Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBt_lib\&.c\fP"
.br
.RI "\fIInitialize CUnit framework and unit tests for add\&. \fP"
.in -1c
