.TH "src/lib.c" 3 "Mon Mar 24 2014" "Version 0.95" "CUnit Test Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lib.c \- 
.PP
Implements add\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'lib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBadd\fP (int a, int b)"
.br
.RI "\fIAdds two ints together\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implements add\&. 


.PP
\fBDate:\fP
.RS 4
3/20/14 
.RE
.PP
\fBAuthor:\fP
.RS 4
Owen Watson
.RE
.PP
.SS "Description"
.PP
This is the implementation of the add function\&. Pretty much magic is happening here\&. No need for documenting this instance of \fBadd(int a, int b)\fP as it is already documented in \fBlib\&.h\fP 
.PP
Definition in file \fBlib\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "int add (inta, intb)"

.PP
Adds two ints together\&. 
.SS "Description"
.PP
This function takes an integer (a) and a second integer (b) and adds them together\&. The result is returned as an int\&.
.PP
\fBParameters:\fP
.RS 4
\fIa\fP the first term to be added 
.br
\fIb\fP the second term to be added
.RE
.PP
\fBReturns:\fP
.RS 4
the resultant integer 
.RE
.PP

.PP
Definition at line 14 of file lib\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CUnit Test Project from the source code\&.
